# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginandregistration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_text', models.TextField()),
                ('quote_author', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('favorites', models.ManyToManyField(related_name='favorite_quotes', to='loginandregistration.User')),
                ('quote_posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_users', to='loginandregistration.User')),
            ],
        ),
    ]
